name: Continuous integration
on:
  push:
    branches:
      - main

jobs:
  ci-python:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          architecture: x64
          cache: pip
          python-version: '3.10'
      - name: pip install
        run: 'pip install -r python/requirements.txt

          pip install -e python/

          '
      - id: measurement-4
        name: Record Measurement After pip install
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: pip install
          task: get-measurement
      - env:
          TEST_WANDB: true
        name: pytest
        run: 'cd python && pytest

          '
      - id: measurement-6
        name: Record Measurement After pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: pytest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740237320.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740237320.json
